# Generated by Django 4.0.3 on 2022-04-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy_webpage', '0002_alter_searches_first_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='searches',
            name='connector',
            field=models.CharField(choices=[('and', 'and'), ('or', 'or')], default='and', max_length=5),
        ),
        migrations.AddField(
            model_name='searches',
            name='second_query',
            field=models.CharField(default='and', max_length=245),
            preserve_default=False,
        ),
    ]
