# Generated by Django 4.0.3 on 2022-04-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy_webpage', '0004_alter_searches_connector_alter_searches_first_query_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searches',
            name='connector',
            field=models.CharField(choices=[('A', 'and'), ('O', 'or')], default='A', max_length=100),
        ),
    ]
