# Generated by Django 4.0.3 on 2022-04-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy_webpage', '0005_alter_searches_connector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searches',
            name='connector',
            field=models.CharField(choices=[('X', ''), ('A', 'and'), ('O', 'or')], default='X', max_length=100),
        ),
    ]
