# Generated by Django 4.0.3 on 2022-04-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy_webpage', '0007_alter_searches_connector'),
    ]

    operations = [
        migrations.AddField(
            model_name='searches',
            name='cleaned_data',
            field=models.CharField(default='X', max_length=200),
        ),
        migrations.AddField(
            model_name='searches',
            name='raw_data',
            field=models.CharField(default='X', max_length=200),
        ),
    ]
